@startsalt
{+
  {
    <b>KARTIKA MAS</b> | Beranda | Paket Umroh | Cara Pendaftaran | Tentang Kami | Kontak | Masuk | Daftar
  }
  ==
  {+
    ..
    ..
    <b><size:24>Kartika Mas Tour & Travel</size></b>
    Kartika Mas Tour & Travel adalah mitra terpercaya dalam memfasilitasi perjalanan ibadah
    ke kota suci Mekkah dan Madinah. Dengan komitmen yang kuat terhadap keunggulan,
    kami mengkhususkan diri untuk menciptakan pengalaman yang tak terlupakan bagi para
    jamaah yang melakukan perjalanan ibadah umroh dan haji bersama kami.
    --
    [ ^search^ Cari Paket Umroh ] | [ ^headphone^ Konsultasi Gratis ]
    ..
    ..
  }
}
@endsalt
