@startsalt
{#
  {
    <b>[ GAMBAR LOGO ]</b>
    [ SLIDE BAR ]
    .
    Dashboard
    Kelola Paket
    Data Jemaah
    Transaksi
    Laporan
    .
    .
    .
    .
    .
    .
    .
    --
    Admin Kartika | ADMIN
  } | {
    {
      <b><size:16>Laporan & Analisis Bisnis</size></b> | "                                  " | ^Periode: Keseluruhan (All-Time)^ | [ [ Ikon PDF ] Download PDF ] | [ Notif ] | [ Keluar -> ]
    }
    ==
    {+
      ====================================================================================================
      <b>Dashboard Laporan Kartika Mas Tour & Travel</b>
      ====================================================================================================
    }
    ==
    {
      {+
        TOTAL OMSET (PAID)               [ Ikon ]
        .
        <b>Rp 15.000.000</b>
      } | {+
        TOTAL TRANSAKSI SUKSES           [ Ikon ]
        .
        <b>100 Trx</b>
      } | {+
        TOTAL JEMAAH AKTIF               [ Ikon ]
        .
        <b>70 Jemaah</b>
      }
    }
    ==
    {
      {+
        <b>Tren Pendapatan Bulanan</b>
        .
        .
        .
        .
        .
        [ GAMBAR GRAFIK GARIS TREN ]
        .
        .
        .
        .
        .
      } | {+
        <b>Komposisi Status Pemesanan</b>
        .
        [ GAMBAR GRAFIK LINGKARAN ]
        .
        () Pending
        () Success
        () Expired
        () Cancel
      }
    }
  }
}
@endsalt
