@startsalt
{+
  {
    <b>KARTIKA MAS</b> | Beranda | Paket Umroh | Cara Pendaftaran | Tentang Kami | Kontak | Masuk | Daftar
  }
  ==
  {
    {+
      [ Gambar Promo ]
      <b>Umroh Premium (Jul & Ags)</b>
      ^calendar^ Berangkat: 20 Jul 2026
      ^plane^ Maskapai: Saudi Airlines
      ^people^ Sisa Kuota: 20/21
      --
      <color:gray>Mulai dari</color>
      <b><color:darkred><size:16>Rp 150.000</size></color></b>
      [        <b>Lihat Detail -></b>       ]
    } | {+
      [ Gambar Promo ]
      <b>Umroh New Season (Jul, Ags, Sep)</b>
      ^calendar^ Berangkat: 15 Aug 2026
      ^plane^ Maskapai: Saudi Airlines
      ^people^ Sisa Kuota: 25/25
      --
      <color:gray>Mulai dari</color>
      <b><color:darkred><size:16>Rp 100.000</size></color></b>
      [        <b>Lihat Detail -></b>       ]
    } | {+
      [ Gambar Promo ]
      <b>Umroh Premium September</b>
      ^calendar^ Berangkat: 10 Sep 2026
      ^plane^ Maskapai: Saudi Airlines
      ^people^ Sisa Kuota: 25/25
      --
      <color:gray>Mulai dari</color>
      <b><color:darkred><size:16>Rp 125.000</size></color></b>
      [        <b>Lihat Detail -></b>       ]
    }
  }
}
@endsalt
